### PR TITLE
AEGIS-165 Add role instances to Roles page

### PR DESCRIPTION
**Pull request by jeffsieu**
image

### CODE REVIEW

**Comment by gjlam95** [comment]
Think can afford to put in A2 (AM) & A2 (PM) as mock data too. Remember that A2 (AM) does not result in a 'Duty Off' the next day

**Comment by jeffsieu** [comment]
Rip, those rules aren't implemented yet at all. As of now each "variant" is treated equally with no special cases

**Comment by gjlam95** [comment]
> Rip, those rules aren't implemented yet at all. As of now each "variant" is treated equally with no special cases

No worries. More important to have these role instances than the special cases haha

**Comment by jeffsieu** [comment]
> Think can afford to put in A2 (AM) & A2 (PM) as mock data too. Remember that A2 (AM) does not result in a 'Duty Off' the next day
> 
> `Standby` can abbreviate as `Stby` to align to what they are familiar with

Done

**Pull request merged**
